spring:
  application:
    name: grader
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3307/grader}
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  flyway:
    enabled: true
    locations: classpath:db/migration
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3307/grader}
    user: root
    password: password
    connect-retries: 10

server:
  servlet:
    context-path: /grader-service
  port: 8000


security:
  enabled: true
  jwt:
    secret-key: mySecretKey123456789012345678901234
    expiration:
      access-token: 3600000 # 1 hour
      refresh-token: 604800000 # 7 days

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

sandbox:
  python:
    url: http://localhost:8001
  java:
    url: http://localhost:8002
