spring:
  application:
    name: grader
  datasource:
    url:  ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3307/grader}
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

security:
  jwt:
    secret-key: mySecretKey123456789012345678901234


server:
  servlet:
    context-path: /grader-service
  port: 8000

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true