CREATE TABLE IF NOT EXISTS problems (
    problem_id BIGINT NOT NULL AUTO_INCREMENT,
    title VARCHAR(255) NOT NULL,
    description VARCHAR(255) NOT NULL,
    difficulty ENUM('EASY','MEDIUM','HARD') NOT NULL,
    type ENUM('MATH','DATA_STRUCTURE','GRAPH','STRING') NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (problem_id)
);
